# Generated by Django 3.0.4 on 2020-03-07 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='dateCreated',
            new_name='date',
        ),
    ]
